application: blogofile-gae-demo
version: 1
runtime: python
api_version: 1

handlers:

- url: /css
  static_dir: css
  
- url: /js
  static_dir: js

- url: /site_img
  static_dir: site_img  
  
- url: /
  script: main.py
  
- url: .*
  script: main.py  
